language: node_js
node_js:
  - 6.2.2
after_script:
  - git describe --tags --exact-match 2>/dev/null
  - echo $?
notifications:
  slack: liiveteam:Aj7V8m8n5p2GGf3F4cHTiv3W
  branches:
    only:
    - master
    - develop
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: npm
  api_key: $NPM_KEY
  email: "robblovell@gmail.com"
  on:
    tags: true
    branch: master
  skip_cleanup: true
  clean_up: false
  repo: liivevideo/react-native-web-webrtc

