language: node_js

node_js:
   - "6.2.2"

deploy:
  provider: npm
  api_key: $NPM_KEY
  email: "robblovell@gmail.com"
  on:
    tags: true
    branch: master
  skip_cleanup: true

notifications:

  slack: liiveteam:Aj7V8m8n5p2GGf3F4cHTiv3W
  branches:
    only:
      - master
      - develop
    on_success: change
    on_failure: always
    on_start: never
